// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IModel is an autogenerated mock type for the IModel type
type IModel struct {
	mock.Mock
}

// GetId provides a mock function with given fields:
func (_m *IModel) GetId() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// SetId provides a mock function with given fields: id
func (_m *IModel) SetId(id string) {
	_m.Called(id)
}
